# -*- mode: dockerfile -*-
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#
# Python MXNet Dockerfile

ARG BASE_IMAGE
FROM ${BASE_IMAGE}

ARG USER_ID=1001
ARG GROUP_ID=1001

RUN apt update && apt install -y python3 python3-pip
RUN pip3 install nose 'numpy<=1.15.2,>=1.8.2' 'requests<2.19.0,>=2.18.4' h5py==2.8.0rc1 scipy==1.0.1

RUN groupadd --gid $GROUP_ID --system jenkins_slave
RUN useradd -m --no-log-init --uid $USER_ID --gid $GROUP_ID --system jenkins_slave

RUN mkdir -p /mxnet && chown -R jenkins_slave /mxnet

WORKDIR /mxnet
